# Generated by Django 5.0.4 on 2024-04-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccount_organisation'),
        ('organisations', '0004_alter_organisation_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='organisations.organisation'),
        ),
    ]
