# Generated by Django 5.0.4 on 2024-04-21 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_farm', '0004_alter_organisation_org_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
