# Generated by Django 5.0.4 on 2024-04-29 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='organisation',
            name='industry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='organisations.industry'),
        ),
    ]
