# Generated by Django 5.0.4 on 2024-04-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_industry_organisation_address_organisation_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.TextField(default='1'),
        ),
    ]
