# Generated by Django 5.0.4 on 2024-04-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_alter_organisation_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='industry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_industry', to='organisations.industry'),
        ),
    ]
